export default [
  {
    id: 1,
    key: '1-Dashboard',
    label: 'Dashboard',
    path: '/dashboard',
    icon: 'Home',
    iconFavorite: 'Home',
    isFavorite: 0,
    breadcrumb: 'Dashboard',
  },
  {
    id: 2,
    key: '2-Seguranca',
    label: 'Segurança',
    icon: 'Settings',
    nodes: [
      {
        id: 3,
        key: '3-Usuarios',
        label: 'Usuarios',
        path: '/dashboard/seguranca/usuarios',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'Segurança > Usuarios',
      },
      {
        id: 21,
        key: '21-Permissoes',
        label: 'Permissões',
        path: '/dashboard/seguranca/permissoes',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'Segurança > Usuarios',
      },
      /* {
        id: 4,
        key: '4-Perfis',
        label: 'Perfis',
        path: '/dashboard/seguranca/perfis',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'Segurança > Perfis',
      }, */
      /* {
        id: 5,
        key: '5-ClonarPermissoes',
        label: 'Clonar Permissões',
        path: '/dashboard/seguranca/clonar-permissoes',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'Segurança > Clonar Permissões',
      }, */
      /* {
        id: 6,
        key: '6-Empresa',
        label: 'Empresa',
        path: '/dashboard/seguranca/empresa',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'Segurança > Empresa',
      }, */
      /* {
        id: 7,
        key: '7-Senha',
        label: 'Senha',
        path: '/dashboard/seguranca/senha',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'Segurança > Senha',
      }, */
      {
        id: 26,
        key: '26-Fazenda',
        label: 'Fazenda',
        path: '/dashboard/seguranca/fazenda',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'Segurança > Senha',
      },
    ],
  },
  {
    id: 8,
    key: '8-RecursosHumanos',
    label: 'Recursos Humanos',
    icon: 'PeopleAlt',
    nodes: [
      {
        id: 9,
        key: '9-Funcionarios',
        label: 'Funcionarios',
        path: '/dashboard/recursos-humanos/funcionarios',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'Recursos Humanos > Funcionarios',
      },
      /* {
        id: 10,
        key: '10-HorasExtras',
        label: 'Horas Extras',
        path: '/dashboard/recursos-humanos/horas-extras',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'Recursos Humanos > Horas Extras',
      }, */
      /* {
        id: 11,
        key: '11-AgendarFerias',
        label: 'Agendar Ferias',
        path: '/dashboard/recursos-humanos/agendar-ferias',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'Recursos Humanos > Agendar Ferias',
      }, */
      /* {
        id: 12,
        key: '12-LancarProducao',
        label: 'Lançar Produção',
        path: '/dashboard/recursos-humanos/lancar-producao',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'Recursos Humanos > Lançar Produção',
      }, */
      /* {
        id: 13,
        key: '13-Equipes',
        label: 'Equipes',
        path: '/dashboard/recursos-humanos/equipes',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'Recursos Humanos > Equipes',
      }, */
      {
        id: 14,
        key: '14-CargosFuncoes',
        label: 'Cargos / Funcoes',
        path: '/dashboard/recursos-humanos/cargos-funcoes',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'Recursos Humanos > Cargos / Funcoes',
      },
    ],
  },
  /* {
    id: 15,
    key: '15-Financeiro',
    label: 'Financeiro',
    icon: 'AttachMoney',
    nodes: [
      {
        id: 16,
        key: '16-x',
        label: '...',
        path: '...',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'Financeiro > ...',
      },
    ],
  },
  {
    id: 17,
    key: '17-Almoxarifado',
    label: 'Almoxarifado',
    icon: 'Store',
    nodes: [
      {
        id: 18,
        key: '18-x',
        label: '...',
        path: '...',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'Almoxarifado > ...',
      },
    ],
  },
  {
    id: 19,
    key: '19-Bi',
    label: 'BI',
    icon: 'Timeline',
    nodes: [
      {
        id: 20,
        key: '20-x',
        label: '...',
        path: '...',
        iconFavorite: 'Person',
        isFavorite: 0,
        breadcrumb: 'BI > ...',
      },
    ],
  }, */
];
